---
# roles/ansible_role_dnsmasq_localdns/tasks/main.yml

- name: Load dnsmasq hosts
  ansible.builtin.include_vars:
    file: dnsmasq_hosts.yml

- name: Ensure DNSStubListener is set to "no" in resolved.conf
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSStubListener='
    line: 'DNSStubListener=no'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
    create: true
    backup: true
  notify: Restart systemd-resolved

- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present

- name: Ensure directory exists
  ansible.builtin.file:
    path: /etc/dnsmasq.d
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: Template dnsmasq.conf.j2 to /etc/dnsmasq.d/dnsmasq.conf
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/dnsmasq.conf
    owner: root
    group: root
    mode: 'u=r,g=r,o=r'
  notify: Restart dnsmasq

- name: Template hosts.dnsmasq.j2 to /etc/hosts.dnsmasq
  ansible.builtin.template:
    src: hosts.dnsmasq.j2
    dest: /etc/hosts.dnsmasq
    owner: root
    group: root
    mode: 'u=r,g=r,o=r'
  notify: Restart dnsmasq

- name: Enable dnsmasq service
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
